### ISSUE TITLE
[Tracking] pre 0.9 transition

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/w3-protocol#95]
Housekeeping work before transition to 0.9

- [x] #98
- [x] Deploy staging and check with @ice-breaker-tg
- [x] Make `0.8` branch
- [x] Change worker name to `w3access-0.8`
- [x] Change custom domain to `access-0.8.web3.storage` and make sure w3up client/cli default to it
